### ISSUE TITLE
Update README.md with the latest release info

### ISSUE THREAD

**Issue by parubok** [sshtools/icon-generator#1]
Hi!

Please update the README.md file to mention the latest released version of the library.
On the Maven central, the latest release is 1.2, but the README.md file mentions version 1.0.3 in the Maven dependency description.
Also, please mention that version 1.2 requires Java 9 or later.

And thanks for the cool project!

Eli

**Comment by brett-smith** [comment]
Thanks for the feedback! The README.md has been corrected.
